server:
  port: 8080
spring:
  application:
    name: ashok-employee-service
eureka:
  instance:
    secure-port-enabled: false
    non-secure-port-enabled: true
    hostname: ${vcap.application.uris[0]:localhost}
    instanceId: ${spring.application.name}:${vcap.application.instance_id:localhost}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      healthcheck:
        enabled: true
logging:
  level:
    org.springframework: INFO
    com.ashok.employee.rest: DEBUG
    root: info
  pattern:
    console: '%-5level %logger{36} - %msg%n'